import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import Headers from "../components/Header/Header";
import Footers from "../components/Footer/Footer";
import "bootstrap/dist/css/bootstrap.min.css";
import { CartContextProvider } from "@/hooks/useCart";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt_BR">
      <CartContextProvider>
        <body className={inter.className}>
          <Headers />
          {children}

          <Footers />
        </body>
      </CartContextProvider>
    </html>
  );
}
